# Generated by Django 4.2.7 on 2025-07-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置项的唯一标识', max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(help_text='配置项的值', verbose_name='配置值')),
                ('description', models.CharField(blank=True, help_text='配置项的说明', max_length=200, verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['key'],
            },
        ),
    ]
