# Generated by Django 4.2.7 on 2025-07-20 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, help_text='用户手机号码', max_length=11, null=True, verbose_name='手机号')),
                ('birth_date', models.DateField(blank=True, help_text='用户生日', null=True, verbose_name='生日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('is_email_verified', models.BooleanField(default=False, help_text='用户邮箱是否已通过验证', verbose_name='邮箱已验证')),
                ('email_verification_token', models.CharField(blank=True, help_text='用于邮箱验证的令牌', max_length=100, null=True, verbose_name='邮箱验证令牌')),
                ('email_verification_token_created', models.DateTimeField(blank=True, help_text='邮箱验证令牌的创建时间', null=True, verbose_name='验证令牌创建时间')),
                ('is_banned', models.BooleanField(default=False, help_text='用户是否被系统封禁', verbose_name='是否被封禁')),
                ('ban_reason', models.CharField(blank=True, help_text='用户被封禁的原因', max_length=200, null=True, verbose_name='封禁原因')),
                ('ban_until', models.DateTimeField(blank=True, help_text='用户封禁的到期时间，为空表示永久封禁', null=True, verbose_name='封禁到期时间')),
                ('login_failure_count', models.PositiveIntegerField(default=0, help_text='连续登录失败的次数', verbose_name='登录失败次数')),
                ('last_login_failure_time', models.DateTimeField(blank=True, help_text='最后一次登录失败的时间', null=True, verbose_name='最后登录失败时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profiles',
            },
        ),
    ]
