# Generated by Django 4.2.7 on 2025-07-20 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='下单时的商品名称（快照）', max_length=200, verbose_name='商品名称')),
                ('seckill_price', models.DecimalField(decimal_places=2, help_text='下单时的秒杀价格（快照）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='秒杀价格')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='购买商品数量', validators=[django.core.validators.MinValueValidator(1)], verbose_name='购买数量')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='订单总金额', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='订单总额')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending_payment', help_text='订单当前状态', max_length=20, verbose_name='订单状态')),
                ('payment_deadline', models.DateTimeField(blank=True, help_text='订单支付截止时间，超时将自动取消', null=True, verbose_name='支付截止时间')),
                ('paid_at', models.DateTimeField(blank=True, help_text='订单支付完成时间', null=True, verbose_name='支付时间')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='订单取消时间', null=True, verbose_name='取消时间')),
                ('cancel_reason', models.CharField(blank=True, help_text='订单取消原因', max_length=200, verbose_name='取消原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(help_text='关联的秒杀活动', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='activities.seckillactivity', verbose_name='秒杀活动')),
                ('user', models.ForeignKey(help_text='下单用户', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(condition=models.Q(('status', 'pending_payment')), fields=['payment_deadline'], name='idx_orders_deadline_pending')],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'activity'), name='unique_user_activity_order'),
        ),
    ]
