# Generated by Django 4.2.7 on 2025-07-20 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='秒杀活动的名称', max_length=200, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, help_text='秒杀活动的详细描述', verbose_name='活动描述')),
                ('start_time', models.DateTimeField(help_text='秒杀活动开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='秒杀活动结束时间', verbose_name='结束时间')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='商品原始价格', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='原价')),
                ('seckill_price', models.DecimalField(decimal_places=2, help_text='秒杀活动价格', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='秒杀价')),
                ('total_stock', models.PositiveIntegerField(help_text='秒杀活动总库存数量', validators=[django.core.validators.MinValueValidator(1)], verbose_name='总库存')),
                ('available_stock', models.PositiveIntegerField(help_text='当前可用库存数量', verbose_name='可用库存')),
                ('max_per_user', models.PositiveIntegerField(default=1, help_text='每个用户最多可购买数量', validators=[django.core.validators.MinValueValidator(1)], verbose_name='每人限购')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='pending', help_text='秒杀活动当前状态', max_length=20, verbose_name='活动状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(help_text='参与秒杀的商品', on_delete=django.db.models.deletion.CASCADE, related_name='seckill_activities', to='products.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status', 'start_time'], name='activities__status_d153b3_idx'), models.Index(fields=['product', 'status'], name='activities__product_0447e8_idx'), models.Index(fields=['start_time', 'end_time'], name='activities__start_t_58d33b_idx')],
            },
        ),
    ]
