# Generated by Django 4.2.7 on 2025-07-20 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品分类的名称', max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, help_text='商品分类的详细描述', verbose_name='分类描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='分类显示顺序，数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='是否在前端显示此分类', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, help_text='上级分类，为空表示顶级分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品的名称', max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, help_text='商品的详细描述', verbose_name='商品描述')),
                ('image_url', models.URLField(blank=True, help_text='商品主图的URL地址', max_length=500, verbose_name='商品图片')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='商品的原始价格', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='原价')),
                ('is_active', models.BooleanField(default=True, help_text='商品是否在前端显示', verbose_name='是否上架')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='商品显示顺序，数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, help_text='商品所属分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['is_active', 'sort_order'], name='products_pr_is_acti_779f60_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='products_ca_parent__1cafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['sort_order'], name='products_ca_sort_or_c50e68_idx'),
        ),
    ]
